apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: b7uab8bfu-go 
  janus-idp.io/tekton: b7uab8bfu-go
  backstage.io/kubernetes-id: b7uab8bfu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b7uab8bfu-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  