apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: b7uab8bfu-go-gitops
  description: This is GitOps manifest for b7uab8bfu-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=b7uab8bfu-go
    backstage.io/kubernetes-id: b7uab8bfu-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: b7uab8bfu-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:b7uab8bfu-go
